Repository FppEpitech/Zappy, pull requests merged in 2024-05, with the labels that each got.

#2 feat: issue templates for features
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#6 Feat/create the gui makefile and main file
  gui/Makefile
  gui/include/.gitkeep
  gui/src/main.cpp
  gui/tests/.gitkeep
Labels: enhancement

#7 doc: CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#13 Feat/create the network class for gui
  gui/Makefile
  gui/include/.gitkeep
  gui/include/Error/AError.hpp
  gui/include/Error/Error.hpp
  gui/include/Error/IError.hpp
  gui/include/Network/Network.hpp
  gui/src/Error/Error.cpp
  gui/src/Network/Network.cpp
  gui/tests/.gitkeep
  gui/tests/Network/TestNetwork.cpp
Labels: enhancement, tests

#12 feat (ci): chocolatine
  .github/workflows/mirror.yml
  .gitignore
  Makefile
  ai/Makefile
  gui/Makefile
  server/Makefile
Labels: enhancement, continuous integration

#16 Feat/gui parsing server commands
  gui/Makefile
  gui/include/Error/Error.hpp
  gui/include/Parsing/ServerParser.hpp
  gui/src/Error/Error.cpp
  gui/src/Network/Network.cpp
  gui/src/Parsing/ServerParser.cpp
  gui/tests/Parsing/TestParser.cpp
Labels: enhancement, tests

#19 Feat/create the engine class gui
  gui/Makefile
  gui/include/Engine/Engine.hpp
  gui/include/Error/Error.hpp
  gui/include/Parsing/ParseCommandLine.hpp
  gui/src/Engine/Engine.cpp
  gui/src/Error/Error.cpp
  gui/src/Network/Network.cpp
  gui/src/Parsing/ParseCommandLine.cpp
  gui/src/main.cpp
  gui/tests/Parsing/TestParseCommandLine.cpp
Labels: enhancement
