Repository FppEpitech/Zappy, pull requests merged in 2024-06, with the labels that each got.

#24 Implemente system of list : ZAPPY Server
  .github/workflows/mirror.yml
  server/Makefile
  server/include/list/list.h
  server/include/list/type.h
  server/src/list/add.c
  server/src/list/list.c
  server/src/list/remove.c
  server/tests/list/list_test.c
Labels: enhancement, tests

#26 Feat/implement the player and inventory class
  gui/Makefile
  gui/include/Player/Inventory.hpp
  gui/include/Player/Player.hpp
  gui/src/Player/Inventory.cpp
  gui/src/Player/Player.cpp
  gui/tests/Player/TestInventory.cpp
  gui/tests/Player/TestPlayer.cpp
Labels: enhancement, tests

#29 Feat/implement the tile class zappy gui
  gui/Makefile
  gui/include/GameDatas/Inventory.hpp
  gui/include/GameDatas/Player.hpp
  gui/include/GameDatas/Tile.hpp
  gui/src/GameDatas/Inventory.cpp
  gui/src/GameDatas/Player.cpp
  gui/src/GameDatas/Tile.cpp
  gui/tests/GameDatas/TestInventory.cpp
  gui/tests/GameDatas/TestPlayer.cpp
  gui/tests/GameDatas/TestTile.cpp
Labels: enhancement, tests

#35 feat: Team class zappy gui
  gui/Makefile
  gui/include/GameDatas/Team.hpp
  gui/src/GameDatas/Team.cpp
Labels: enhancement

#38 feat: add tests for the team zappy gui
  gui/Makefile
  gui/include/GameDatas/Team.hpp
  gui/src/GameDatas/Team.cpp
  gui/tests/CriterionHeaders.hpp
  gui/tests/GameDatas/TestInventory.cpp
  gui/tests/GameDatas/TestPlayer.cpp
  gui/tests/GameDatas/TestTeam.cpp
  gui/tests/GameDatas/TestTile.cpp
  gui/tests/Network/TestNetwork.cpp
  gui/tests/Parsing/TestParseCommandLine.cpp
  gui/tests/Parsing/TestParser.cpp
Labels: bug, enhancement

#43 Feat/add readme to install raylib zappy gui
  gui/README.md
Labels: documentation

#33 feat: Render class to draw the scene
  .github/workflows/mirror.yml
  gui/Makefile
  gui/include/Engine/Engine.hpp
  gui/include/Render/Render.hpp
  gui/include/Render/UserCamera.hpp
  gui/src/Engine/Engine.cpp
  gui/src/Render/Render.cpp
  gui/src/Render/UserCamera.cpp
  gui/tests/Render/TestCamera.cpp
Labels: enhancement

#46 Feat: implement the gamedata class zappy gui
  gui/Makefile
  gui/include/Error/Error.hpp
  gui/include/GameDatas/GameData.hpp
  gui/src/Error/Error.cpp
  gui/src/GameDatas/GameData.cpp
  gui/tests/GameDatas/TestGameData.cpp
Labels: enhancement

#45 feat: Event class for events up and down camera and debug display
  gui/Makefile
  gui/include/Engine/Engine.hpp
  gui/include/Event/Event.hpp
  gui/include/Render/Render.hpp
  gui/src/Engine/Engine.cpp
  gui/src/Event/Event.cpp
  gui/src/Render/Render.cpp
  gui/src/main.cpp
Labels: enhancement

#56 Feat/display food and resources zappy gui
  gui/assets/deraumere.glb
  gui/assets/food.glb
  gui/assets/linemate.glb
  gui/assets/mendiane.glb
  gui/assets/phiras.glb
  gui/assets/sibur.glb
  gui/assets/thystame.glb
  gui/assets/tile.glb
  gui/include/Assets.hpp
  gui/include/Render/Render.hpp
  gui/src/Render/Render.cpp
Labels: enhancement

#55 Feat/implement parsing of arguments zappy server
  server/Makefile
  server/include/.gitkeep
  server/include/parsing.h
  server/include/rules.h
  server/include/types.h
  server/src/main.c
  server/src/parsing/arguments.c
  server/src/parsing/help.c
  server/src/parsing/parse_client.c
  server/src/parsing/parse_frequency.c
  server/src/parsing/parse_height.c
  server/src/parsing/parse_names.c
  server/src/parsing/parse_port.c
  server/src/parsing/parse_positive_int.c
  server/src/parsing/parse_width.c
  server/tests/.gitkeep
  server/tests/parsing/help_test.c
  server/tests/parsing/parse_arguments_tests.c
  server/tests/parsing/parse_client_tests.c
  server/tests/parsing/parse_frequency_tests.c
  server/tests/parsing/parse_height_tests.c
  server/tests/parsing/parse_names_tests.c
  server/tests/parsing/parse_port_tests.c
  server/tests/parsing/parse_positive_int_tests.c
  server/tests/parsing/parse_width_tests.c
Labels: enhancement

#59 Feat/implement the update of the gamedata class zappy gui
  gui/include/Error/Error.hpp
  gui/include/GUIUpdater/GUIUpdater.hpp
  gui/include/GameDatas/GameData.hpp
  gui/include/GameDatas/Inventory.hpp
  gui/include/GameDatas/Player.hpp
  gui/include/GameDatas/Tile.hpp
  gui/src/Engine/Engine.cpp
  gui/src/Error/Error.cpp
  gui/src/GUIUpdater/GUIUpdater.cpp
  gui/src/GameDatas/GameData.cpp
  gui/src/GameDatas/Inventory.cpp
  gui/src/GameDatas/Player.cpp
  gui/src/GameDatas/Tile.cpp
  gui/src/Render/Render.cpp
  gui/tests/GUIUpdater/TestGUIUpdater.cpp
  gui/tests/GameDatas/TestGameData.cpp
  gui/tests/GameDatas/TestInventory.cpp
  gui/tests/GameDatas/TestPlayer.cpp
  gui/tests/GameDatas/TestTeam.cpp
  gui/tests/GameDatas/TestTile.cpp
Labels: enhancement

#52 Implement connection and responde on server
  server/Makefile
  server/include/ai/ai.h
  server/include/ai/team.h
  server/include/app/app.h
  server/include/game/game.h
  server/include/gui/gui.h
  server/include/list/type.h
  server/include/server/client.h
  server/include/server/server.h
  server/src/ai/ai.c
  server/src/ai/team.c
  server/src/app/app.c
  server/src/game/game.c
  server/src/gui/gui.c
  server/src/main.c
  server/src/server/client.c
  server/src/server/quit.c
  server/src/server/read/connection.c
  server/src/server/read/read_data.c
  server/src/server/run.c
  server/src/server/server.c
  server/src/server/write/write_data.c
  server/tests/communication/communication_test.c
Labels: enhancement

#63 Feat/display players zappy gui
  gui/Makefile
  gui/assets/player.glb
  gui/include/Assets.hpp
  gui/include/GameDatas/GameData.hpp
  gui/include/GameDatas/Team.hpp
  gui/include/Render/Render.hpp
  gui/src/GUIUpdater/GUIUpdater.cpp
  gui/src/GameDatas/GameData.cpp
  gui/src/GameDatas/Team.cpp
  gui/src/Render/Render.cpp
  gui/tests/GUIUpdater/TestGUIUpdater.cpp
  gui/tests/GameDatas/TestGameData.cpp
  gui/tests/GameDatas/TestTeam.cpp
Labels: enhancement

#51 feat: naming conventions, doxygen, includes in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, enhancement

#67 Feat/implement tick and call server updates zappy gui
  gui/include/Engine/Engine.hpp
  gui/include/GameDatas/GameData.hpp
  gui/include/Network/Network.hpp
  gui/src/Engine/Engine.cpp
  gui/src/GUIUpdater/GUIUpdater.cpp
  gui/src/GameDatas/GameData.cpp
  gui/src/Network/Network.cpp
  gui/tests/GUIUpdater/TestGUIUpdater.cpp
Labels: enhancement, tests

#70 Feat/implement player status zappy gui
  gui/include/GameDatas/Player.hpp
  gui/src/GameDatas/Player.cpp
  gui/tests/GameDatas/TestPlayer.cpp
Labels: enhancement, tests

#73 feat: handle seg command server (end of game)
  gui/include/GameDatas/GameData.hpp
  gui/src/Engine/Engine.cpp
  gui/src/GUIUpdater/GUIUpdater.cpp
  gui/src/GameDatas/GameData.cpp
  gui/tests/GUIUpdater/TestGUIUpdater.cpp
  gui/tests/GameDatas/TestGameData.cpp
Labels: enhancement, tests

#75 Refactor/move gui binary in root and fix assets zappy gui
  gui/Makefile
  gui/include/Assets.hpp
Labels: enhancement, architecture

#76 Feat/implement the egg class
  gui/Makefile
  gui/assets/egg.glb
  gui/include/Assets.hpp
  gui/include/GameDatas/Egg.hpp
  gui/include/GameDatas/GameData.hpp
  gui/include/GameDatas/Team.hpp
  gui/include/Render/Render.hpp
  gui/src/GUIUpdater/GUIUpdater.cpp
  gui/src/GameDatas/Egg.cpp
  gui/src/GameDatas/GameData.cpp
  gui/src/GameDatas/Team.cpp
  gui/src/Render/Render.cpp
  gui/tests/GUIUpdater/TestGUIUpdater.cpp
  gui/tests/GameDatas/TestEgg.cpp
Labels: enhancement

#61 feat: Create a API class for the AI
  .coveragerc
  .gitignore
  ai/Makefile
  ai/requirement.txt
  ai/src/Errors/ArgsException.py
  ai/src/Errors/IError.py
  ai/src/Network/API.py
  ai/src/Network/APIException.py
  ai/src/Utils/Utils.py
  ai/src/main.py
  ai/tests/.gitkeep
  ai/tests/Errors/TestErrors.py
  ai/tests/MainTest.py
  ai/tests/Network/TestAPI.py
  ai/tests/Utils/TestUtils.py
Labels: enhancement, architecture

#80 feat: send messages for player position at each tick
  gui/src/Engine/Engine.cpp
Labels: enhancement

#84 Feat/add missing tests for the team class zappy gui
  gui/Makefile
  gui/src/GameDatas/GameData.cpp
  gui/src/GameDatas/Team.cpp
  gui/tests/GUIUpdater/TestGUIUpdater.cpp
  gui/tests/GameDatas/TestGameData.cpp
  gui/tests/GameDatas/TestTeam.cpp
Labels: enhancement

#86 Feat/update the guiupdater class thanks to player state zappy gui
  gui/include/Engine/Engine.hpp
  gui/include/GUIUpdater/GUIUpdater.hpp
  gui/include/GameDatas/Egg.hpp
  gui/include/GameDatas/GameData.hpp
  gui/include/GameDatas/Player.hpp
  gui/src/Engine/Engine.cpp
  gui/src/GUIUpdater/GUIUpdater.cpp
  gui/src/GameDatas/Egg.cpp
  gui/src/GameDatas/GameData.cpp
  gui/src/GameDatas/Player.cpp
  gui/src/main.cpp
  gui/tests/GUIUpdater/TestGUIUpdater.cpp
  gui/tests/GameDatas/TestEgg.cpp
  gui/tests/GameDatas/TestGameData.cpp
  gui/tests/GameDatas/TestPlayer.cpp
Labels: enhancement

#92 Implement the Player actions
  ai/Makefile
  ai/src/AI.py
  ai/src/Enum/Action.py
  ai/src/Enum/Item.py
  ai/src/Network/API.py
  ai/src/Player/Inventory.py
  ai/src/Player/Player.py
  ai/src/Player/PlayerException.py
  ai/src/main.py
  ai/tests/MainTest.py
  ai/tests/Network/TestAPI.py
  ai/tests/Player/TestInventory.py
  ai/tests/Player/TestPlayer.py
  ai/tests/TestAI.py
Labels: enhancement

#110 Refactor/find and replace assets zappy gui
  gui/Makefile
  gui/assets/decoration/lantern.glb
  gui/assets/decoration/tree.glb
  gui/assets/deraumere.glb
  gui/assets/egg.glb
  gui/assets/food.glb
  gui/assets/linemate.glb
  gui/assets/mendiane.glb
  gui/assets/phiras.glb
  gui/assets/player/egg.glb
  gui/assets/player/player.glb
  gui/assets/resources/deraumere.glb
  gui/assets/resources/food.glb
  gui/assets/resources/linemate.glb
  gui/assets/resources/mendiane.glb
  gui/assets/resources/phiras.glb
  gui/assets/resources/sibur.glb
  gui/assets/resources/thystame.glb
  gui/assets/sibur.glb
  gui/assets/thystame.glb
  gui/assets/tile.glb
  gui/assets/tile/tile.glb
  gui/include/Assets.hpp
  gui/include/GameDatas/GameData.hpp
  gui/include/Render/Decoration.hpp
  gui/include/Render/Render.hpp
  gui/include/Types.hpp
  gui/src/Render/Decoration.cpp
  gui/src/Render/Render.cpp
  tests/gui/tests/GameDatas/TestTile.cpp
Labels: enhancement

#113 feat: test for Decoration class
  gui/Makefile
  tests/gui/tests/Render/TestDecoration.cpp
Labels: tests

#114 Feat/get players pov zappy gui
  gui/Makefile
  gui/include/Assets.hpp
  gui/include/Event/Event.hpp
  gui/include/GameDatas/GameData.hpp
  gui/include/GameDatas/Player.hpp
  gui/include/GameDatas/Team.hpp
  gui/include/Render/Render.hpp
  gui/include/Render/UserCamera.hpp
  gui/src/Engine/Engine.cpp
  gui/src/Event/Event.cpp
  gui/src/GameDatas/GameData.cpp
  gui/src/GameDatas/Player.cpp
  gui/src/GameDatas/Team.cpp
  gui/src/Render/Render.cpp
  gui/src/Render/UserCamera.cpp
  tests/gui/tests/GameDatas/TestGameData.cpp
  tests/gui/tests/GameDatas/TestPlayer.cpp
  tests/gui/tests/Render/TestUserCamera.cpp
Labels: enhancement

#116 Feat/implement clicks for tiles
  gui/include/Event/Event.hpp
  gui/include/GameDatas/Tile.hpp
  gui/include/Render/Render.hpp
  gui/src/Event/Event.cpp
  gui/src/GameDatas/Tile.cpp
  gui/src/Render/Render.cpp
Labels: enhancement

#121 Implement auto filling of all available slots in the team
  ai/src/AI.py
  ai/src/Player/Inventory.py
  ai/src/Player/Player.py
  ai/src/Player/PlayerException.py
  ai/src/main.py
  tests/ai/tests/Player/TestInventory.py
Labels: enhancement

#104 Feat/implement hud player zappy gui
  gui/Makefile
  gui/assets/hud/SimplyMono-Bold.ttf
  gui/assets/hud/hud.png
  gui/include/Assets.hpp
  gui/include/Event/Event.hpp
  gui/include/Hud/AHud.hpp
  gui/include/Hud/HudGame.hpp
  gui/include/Hud/HudPlayer.hpp
  gui/include/Hud/HudTile.hpp
  gui/include/Hud/IHud.hpp
  gui/include/Render/Render.hpp
  gui/include/Render/UserCamera.hpp
  gui/src/Event/Event.cpp
  gui/src/Hud/AHud.cpp
  gui/src/Hud/HudGame.cpp
  gui/src/Hud/HudPlayer.cpp
  gui/src/Hud/HudTile.cpp
  gui/src/Render/Render.cpp
  gui/src/Render/UserCamera.cpp
Labels: enhancement

#123 Feat/display cursor zappy gui
  gui/assets/hud/cursor.png
  gui/include/Assets.hpp
  gui/include/Render/Render.hpp
  gui/src/Render/Render.cpp
Labels: enhancement

#130 Feat/implement chunks and render distance zappy gui
  gui/include/Assets.hpp
  gui/include/Config.hpp
  gui/include/Event/Event.hpp
  gui/include/Render/Decoration.hpp
  gui/include/Render/Render.hpp
  gui/src/Event/Event.cpp
  gui/src/GameDatas/Player.cpp
  gui/src/GameDatas/Team.cpp
  gui/src/GameDatas/Tile.cpp
  gui/src/Render/Decoration.cpp
  gui/src/Render/Render.cpp
  tests/gui/tests/GameDatas/TestPlayer.cpp
  tests/gui/tests/GameDatas/TestTeam.cpp
  tests/gui/tests/GameDatas/TestTile.cpp
  tests/gui/tests/Render/TestDecoration.cpp
Labels: enhancement

#136 Feat/make time unit changeable zappy gui
  gui/include/Event/Event.hpp
  gui/include/GameDatas/GameData.hpp
  gui/include/Render/Render.hpp
  gui/src/Engine/Engine.cpp
  gui/src/Event/Event.cpp
  gui/src/GUIUpdater/GUIUpdater.cpp
  gui/src/GameDatas/GameData.cpp
  gui/src/Render/Render.cpp
Labels: enhancement

#141 Feat/implement player animations zappy gui
  gui/Makefile
  gui/include/Event/Event.hpp
  gui/include/GameDatas/Player.hpp
  gui/include/GameDatas/Team.hpp
  gui/include/Render/Render.hpp
  gui/src/Engine/Engine.cpp
  gui/src/Event/Event.cpp
  gui/src/GUIUpdater/GUIUpdater.cpp
  gui/src/GameDatas/Player.cpp
  gui/src/GameDatas/Team.cpp
  gui/src/Render/Render.cpp
  gui/src/Render/RenderAnimations.cpp
Labels: enhancement

#145 refactor: change default render distance and max value
  gui/include/Config.hpp
Labels: enhancement

#152 Implemente calcul of k
  server/Makefile
  server/include/ai/cmd/command_ai.h
  server/include/server/server.h
  server/src/ai/cmd/broadcast/broadcast_cmd.c
  server/src/ai/cmd/broadcast/calcul_k.c
  server/src/server/run.c
Labels: enhancement

#127 Feat/implement basic ai reaching level 8 zappy ai
  .gitignore
  ai/src/AI.py
  ai/src/Enum/Mode.py
  ai/src/Network/API.py
  ai/src/Network/APIException.py
  ai/src/Player/Inventory.py
  ai/src/Player/Player.py
  logs/.gitkeep
  tests/ai/tests/Player/TestPlayer.py
Labels: enhancement

#155 Refactor/improve hud understanding zappy gui
  gui/assets/hud/deraumere.png
  gui/assets/hud/food.png
  gui/assets/hud/linemate.png
  gui/assets/hud/mendiane.png
  gui/assets/hud/phiras.png
  gui/assets/hud/player.png
  gui/assets/hud/sibur.png
  gui/assets/hud/thystame.png
  gui/assets/hud/tile.png
  gui/include/Assets.hpp
  gui/include/Hud/HudGame.hpp
  gui/include/Hud/HudPlayer.hpp
  gui/include/Hud/HudTile.hpp
  gui/src/Hud/HudGame.cpp
  gui/src/Hud/HudPlayer.cpp
  gui/src/Hud/HudTile.cpp
Labels: enhancement

#163 Add tna command when gui connected and fix egg apparition
  server/include/ai/team.h
  server/src/ai/cmd/other/fork_cmd.c
  server/src/ai/stuck.c
  server/src/ai/team.c
  server/src/gui/gui.c
Labels: enhancement

#165 fix: player ppo don't stop incantation
  gui/src/GUIUpdater/GUIUpdater.cpp
Labels: bug

#166 Fix/fix the egg dispawn after a player spawns zappy gui
  gui/include/GameDatas/GameData.hpp
  gui/src/GUIUpdater/GUIUpdater.cpp
  gui/src/GameDatas/GameData.cpp
  gui/src/Render/Render.cpp
Labels: enhancement

#169 Feat/add colors to team members zappy gui
  gui/include/Colors.hpp
  gui/include/GUIUpdater/GUIUpdater.hpp
  gui/include/GameDatas/GameData.hpp
  gui/include/GameDatas/Team.hpp
  gui/src/GUIUpdater/GUIUpdater.cpp
  gui/src/GameDatas/GameData.cpp
  gui/src/GameDatas/Team.cpp
  gui/src/Hud/HudGame.cpp
  gui/src/Hud/HudPlayer.cpp
  gui/src/Render/Render.cpp
  tests/gui/tests/GUIUpdater/TestGUIUpdater.cpp
  tests/gui/tests/GameDatas/TestGameData.cpp
  tests/gui/tests/GameDatas/TestTeam.cpp
Labels: enhancement

#160 Feature black line between tiles GUI
  gui/include/Assets.hpp
  gui/include/Config.hpp
  gui/src/Render/Render.cpp
Labels: enhancement

#170 Fix communication beetween client !
  server/include/gui/communication.h
  server/src/ai/ai.c
  server/src/gui/communication/pnw.c
  server/src/gui/gui.c
  server/src/server/write/write_data.c
Labels: enhancement

#172 Feat/implement player level display above their head zappy gui
  gui/include/Render/Render.hpp
  gui/src/Render/Render.cpp
Labels: enhancement

#151 Create tests for communication between server and gui
  server/Makefile
  server/src/gui/communication/mct.c
  server/src/gui/communication/msz.c
  server/src/gui/communication/pgt.c
  server/src/gui/communication/sgt.c
  server/src/gui/communication/tna.c
  tests/server/tests/gui/commands/tests_bct.c
  tests/server/tests/gui/commands/tests_ebo.c
  tests/server/tests/gui/commands/tests_edi.c
  tests/server/tests/gui/commands/tests_enw.c
  tests/server/tests/gui/commands/tests_loop.c
  tests/server/tests/gui/commands/tests_mct.c
  tests/server/tests/gui/commands/tests_msz.c
  tests/server/tests/gui/commands/tests_pbc.c
  tests/server/tests/gui/commands/tests_pdi.c
  tests/server/tests/gui/commands/tests_pdr.c
  tests/server/tests/gui/commands/tests_pex.c
  tests/server/tests/gui/commands/tests_pfk.c
  tests/server/tests/gui/commands/tests_pgt.c
  tests/server/tests/gui/commands/tests_pic.c
  tests/server/tests/gui/commands/tests_pie.c
  tests/server/tests/gui/commands/tests_pin.c
  tests/server/tests/gui/commands/tests_plv.c
  tests/server/tests/gui/commands/tests_pnw.c
  tests/server/tests/gui/commands/tests_ppo.c
  tests/server/tests/gui/commands/tests_sbp.c
  tests/server/tests/gui/commands/tests_seg.c
  tests/server/tests/gui/commands/tests_sgt.c
  tests/server/tests/gui/commands/tests_smg.c
  tests/server/tests/gui/commands/tests_sst.c
  tests/server/tests/gui/commands/tests_suc.c
  tests/server/tests/gui/commands/tests_tna.c
Labels: tests

#175 feat: Display player Broadcast above player level
  gui/include/Assets.hpp
  gui/include/Render/Render.hpp
  gui/src/Render/Render.cpp
Labels: enhancement

#177 fix: The rotation of two flowers to be well placed
  gui/include/Assets.hpp
Labels: enhancement

#180 Feat/create interface to test network zappy gui
  gui/Makefile
  gui/include/Engine/Engine.hpp
  gui/include/GUIUpdater/GUIUpdater.hpp
  gui/include/Network/ANetwork.hpp
  gui/include/Network/INetwork.hpp
  gui/include/Network/Network.hpp
  gui/src/Engine/Engine.cpp
  gui/src/GUIUpdater/GUIUpdater.cpp
  gui/src/Network/ANetwork.cpp
  gui/src/Network/Network.cpp
  tests/gui/tests/GUIUpdater/TestGUIUpdater.cpp
Labels: enhancement, architecture

#168 Remove the blocking "select" in AI
  ai/src/AI.py
  ai/src/Player/Player.py
Labels: enhancement

#185 Improvement of the assignement of the leader/slave role
  ai/src/AI.py
  ai/src/Enum/Role.py
  ai/src/Player/Player.py
  ai/src/main.py
  tests/ai/tests/Player/TestPlayer.py
Labels: enhancement

#186 Feat/make gui code more c++ friendly zappy gui
  gui/Makefile
  gui/include/Engine/Engine.hpp
  gui/include/Event/AEvent.hpp
  gui/include/Event/Event.hpp
  gui/include/Event/IEvent.hpp
  gui/include/GUIUpdater/AGUIUpdater.hpp
  gui/include/GUIUpdater/GUIUpdater.hpp
  gui/include/GUIUpdater/IGUIUpdater.hpp
  gui/include/Parsing/IServerParser.hpp
  gui/include/Parsing/ServerParser.hpp
  gui/src/Engine/Engine.cpp
  gui/src/Event/AEvent.cpp
  gui/src/Event/Event.cpp
  gui/src/GUIUpdater/AGUIUpdater.cpp
  gui/src/GUIUpdater/GUIUpdater.cpp
  gui/src/Render/Decoration.cpp
Labels: enhancement

#191 Remove unnecessary parameter to be able to launch the AI
  ai/src/main.py
Labels: bug

#192 Added food directly at the beggining
  server/src/ai/ai.c
  server/src/ai/die.c
  server/src/gui/gui.c
Labels: enhancement

#187 Fix/spam message server zappy gui
  gui/include/Engine/Engine.hpp
  gui/include/GameDatas/GameData.hpp
  gui/include/GameDatas/Inventory.hpp
  gui/src/Engine/Engine.cpp
  gui/src/GUIUpdater/GUIUpdater.cpp
  gui/src/GameDatas/GameData.cpp
  gui/src/GameDatas/Inventory.cpp
  tests/gui/tests/GUIUpdater/TestGUIUpdater.cpp
Labels: bug

#197 Fix memory leak and valgrind error && ressources generation - zappy server
  server/include/list/type.h
  server/include/map/map.h
  server/src/ai/ai_destroy.c
  server/src/ai/cmd/eject/eject_egg.c
  server/src/ai/cmd/look/look_handler.c
  server/src/ai/cmd/other/set_cmd.c
  server/src/ai/cmd/other/take_cmd.c
  server/src/app/app.c
  server/src/gui/communication/ebo.c
  server/src/gui/communication/edi.c
  server/src/gui/communication/enw.c
  server/src/gui/communication/mct.c
  server/src/gui/communication/pbc.c
  server/src/gui/communication/pdi.c
  server/src/gui/communication/pdr.c
  server/src/gui/communication/pex.c
  server/src/gui/communication/pfk.c
  server/src/gui/communication/pgt.c
  server/src/gui/communication/pic.c
  server/src/gui/communication/pie.c
  server/src/gui/communication/pnw.c
  server/src/gui/communication/seg.c
  server/src/gui/communication/smg.c
  server/src/gui/gui.c
  server/src/map/map.c
  server/src/server/run.c
Labels: enhancement

#199 feat: close GUI if server connection down
  gui/include/Config.hpp
  gui/include/Network/Network.hpp
  gui/src/Engine/Engine.cpp
  gui/src/Network/Network.cpp
Labels: enhancement

#204 feat: display nb total player in team in Game HUD
  gui/src/Hud/HudGame.cpp
Labels: enhancement

#205 fix: Time Unit uninitialized value + wrong conditions
  gui/src/Engine/Engine.cpp
  gui/src/GUIUpdater/GUIUpdater.cpp
  gui/src/GameDatas/GameData.cpp
Labels: enhancement

#207 SST command when, the sst required frequence 0
  server/src/gui/communication/sst.c
Labels: bug

#209 fix: send dead to all ennemy
  server/include/ai/ai.h
  server/include/ai/cmd/command_ai.h
  server/include/server/server.h
  server/src/ai/ai.c
  server/src/ai/cmd/other/dead_cmd.c
  server/src/ai/die.c
  server/src/server/quit.c
  server/src/server/read/read_data.c
  server/src/server/run.c
  server/src/server/write/write_data.c
Labels: enhancement

#211 Fix/crash on server zappy server
  server/src/ai/cmd/broadcast/calcul_k.c
  server/src/ai/team.c
  server/src/app/app.c
  server/src/parsing/destroy_parsing.c
  server/src/server/read/read_data.c
Labels: bug

#213 fix: incantation send response
  server/src/ai/cmd/incantation/incantation_handler.c
  server/src/ai/cmd/incantation/level_up.c
  server/src/ai/cmd/incantation/update_status.c
  server/src/ai/stuck.c
Labels: bug

#214 Feat/add players and eggs in inventory of tile zappy gui
  gui/assets/hud/egg.png
  gui/include/Assets.hpp
  gui/include/Hud/HudTile.hpp
  gui/src/Hud/HudTile.cpp
Labels: enhancement

#225 fix: add missing free with Marius AI
  server/src/ai/cmd/broadcast/calcul_k.c
  server/src/gui/communication/pic.c
  server/src/gui/communication/pie.c
Labels: enhancement

#230 Test/test server connection and buffer
  server/src/ai/ai.c
  server/src/server/server.c
  tests/server/test.sh
Labels: enhancement

#228 Encrypt communication via broadcast - Zappy AI
  ai/src/AI.py
  ai/src/Player/Player.py
  ai/src/Utils/Message.py
  tests/ai/tests/Player/TestPlayer.py
Labels: enhancement

#201 Fix/bug a label level title appears in the gui at the opposite of camera and robot zappy gui
  gui/include/Assets.hpp
  gui/include/Render/Render.hpp
  gui/src/Render/Render.cpp
Labels: enhancement

#232 fix: FPS color according to the rest of the debug
  gui/src/Render/Render.cpp
Labels: enhancement

#234 feat: GamePad controller inputs
  gui/include/Event/Event.hpp
  gui/src/Event/Event.cpp
Labels: enhancement

#237 update the usage message and call print_help in case of error of parsing
  server/include/parsing.h
  server/src/main.c
  server/src/parsing/arguments.c
  server/src/parsing/help.c
  tests/server/tests/parsing/help_test.c
Labels: enhancement

#242 fix: buffer management in Network GUI
  gui/include/Network/ANetwork.hpp
  gui/include/Network/INetwork.hpp
  gui/include/Network/Network.hpp
  gui/src/Engine/Engine.cpp
  gui/src/Network/ANetwork.cpp
  gui/src/Network/Network.cpp
Labels: enhancement

#236 Feat/display only players vision zappy gui
  gui/include/Event/Event.hpp
  gui/include/Render/Decoration.hpp
  gui/include/Render/Render.hpp
  gui/include/Render/UserCamera.hpp
  gui/src/Event/Event.cpp
  gui/src/Render/Decoration.cpp
  gui/src/Render/Render.cpp
  gui/src/Render/UserCamera.cpp
  tests/gui/tests/Render/TestDecoration.cpp
Labels: enhancement

#245 Handle SIGINT signal from user - Zappy AI
  ai/src/AI.py
  ai/src/Network/API.py
  ai/src/main.py
Labels: enhancement

#238 Feat/add a tuto hud for user experience zappy gui
  gui/Makefile
  gui/assets/help/help_menu.png
  gui/assets/help/keys.png
  gui/include/Assets.hpp
  gui/include/Config.hpp
  gui/include/Event/Event.hpp
  gui/include/Hud/AHud.hpp
  gui/include/Hud/HudHelp.hpp
  gui/include/Hud/IHud.hpp
  gui/include/Render/Render.hpp
  gui/src/Event/Event.cpp
  gui/src/Hud/AHud.cpp
  gui/src/Hud/HudHelp.cpp
  gui/src/Render/Render.cpp
Labels: enhancement

#249 Create a buffer for data received from the server - Zappy AI
  ai/src/AI.py
  ai/src/Network/API.py
Labels: enhancement

#251 Feat/implement end screen zappy gui
  gui/Makefile
  gui/assets/end/end_hud.png
  gui/include/Assets.hpp
  gui/include/GameDatas/GameData.hpp
  gui/include/Hud/HudEnd.hpp
  gui/include/Hud/IHud.hpp
  gui/include/Render/Render.hpp
  gui/include/Render/UserCamera.hpp
  gui/src/Engine/Engine.cpp
  gui/src/GUIUpdater/GUIUpdater.cpp
  gui/src/GameDatas/GameData.cpp
  gui/src/Hud/HudEnd.cpp
  gui/src/Render/Render.cpp
  gui/src/Render/UserCamera.cpp
Labels: enhancement

#252 Improve AI algorithm to be more versatile - Zappy AI
  ai/src/AI.py
  ai/src/Enum/Mode.py
  ai/src/Player/Player.py
  tests/ai/tests/Player/TestPlayer.py
Labels: enhancement

#194 Refactor/of the ai code and architecture zappy ai
  ai/src/Player/Player.py
  ai/src/Utils/Utils.py
  doc/ai-doc/doxygen-auto-doc.pdf
  doc/gui-doc/doxygen-auto-doc.pdf
  doc/server-doc/doxygen-auto-doc.pdf
Labels: enhancement, architecture

#254 Fix AI Movement - Zappy AI
  ai/src/Player/Player.py
  ai/src/Utils/Utils.py
Labels: bug

#256 feat: update the doxygen-auto-doc pdfs with recent code
  doc/ai-doc/doxygen-auto-doc.pdf
  doc/gui-doc/doxygen-auto-doc.pdf
  doc/server-doc/doxygen-auto-doc.pdf
Labels: documentation, enhancement

#250 Upgrade/logic server gui zappy server
  gui/src/Engine/Engine.cpp
  gui/src/GUIUpdater/GUIUpdater.cpp
  logs/.gitkeep
  server/Makefile
  server/include/ai/cmd/command_ai.h
  server/include/game/game.h
  server/include/gui/communication.h
  server/include/gui/gui.h
  server/include/server/server.h
  server/src/ai/ai_destroy.c
  server/src/ai/cmd/handler.c
  server/src/app/app.c
  server/src/game/game.c
  server/src/game/win.c
  server/src/gui/communication/mct.c
  server/src/gui/communication/ppo.c
  server/src/gui/communication/seg.c
  server/src/gui/communication/sst.c
  server/src/gui/gui.c
  server/src/gui/handler.c
  server/src/server/read/read_data.c
  server/src/server/run.c
  server/src/server/write/write_data.c
Labels: enhancement

#217 Check if the content to send for set the fd_set of write of select
  server/src/server/run.c
Labels: enhancement

#259 Write unit tests to evaluate our AI algorithm - Zappy AI
  ai/src/Player/Inventory.py
  ai/src/Player/Player.py
  tests/ai/tests/Network/TestAPI.py
  tests/ai/tests/Player/TestInventory.py
  tests/ai/tests/Player/TestPlayer.py
  tests/ai/tests/Utils/TestUtils.py
Labels: tests

#263 Remove default logs for AI actions - Zappy AI
  ai/src/AI.py
  ai/src/Network/API.py
  ai/src/Player/Player.py
  ai/src/main.py
  tests/ai/tests/Network/TestAPI.py
  tests/ai/tests/TestAI.py
Labels: enhancement

#202 Create a smart select it must be blocking if necessary and over a good period of time zappy server
  server/include/ai/stuck.h
  server/include/rules.h
  server/include/server/server.h
  server/include/utils.h
  server/src/ai/die.c
  server/src/ai/stuck.c
  server/src/game/game.c
  server/src/server/run.c
  server/src/server/server.c
  server/src/utils.c
Labels: enhancement

#265 Remove unsafe removing of log files - Zappy AI
  ai/src/AI.py
Labels: bug

#258 fix: 2 mistakes in user_documentation.pdf
  doc/user_documentation.pdf
Labels: documentation

#270 Improve AI documentation - Zappy AI
  ai/README.md
  doc/ai-doc/Zappy-AI-class-diagram.jpg
  doc/ai-doc/Zappy-AI-class-diagram.pdf
Labels: documentation

#269 Fix: server communication zappy server
  server/include/gui/gui.h
  server/src/app/app.c
  server/src/gui/gui.c
  tests/server/tests/communication/communication_test.c
Labels: enhancement

#267 Documentation/improve gui technical use documentation
  doc/gui-doc/Zappy_Gui_Class_Diagram.jpg
  doc/gui-doc/Zappy_Gui_Class_Diagram.pdf
  gui/README.md
Labels: documentation

#276 Test/implement test about server
  Makefile
  server/Makefile
  server/src/parsing/parse_height.c
  server/src/parsing/parse_width.c
  tests/server/tests/ai/test_broadcast_command.c
  tests/server/tests/ai/test_eject_command.c
  tests/server/tests/parsing/parse_height_tests.c
  tests/server/tests/parsing/parse_width_tests.c
Labels: tests

#274 Feat/implement multithreading for network and guiupdater zappy gui
  gui/include/Engine/Engine.hpp
  gui/include/GameDatas/GameData.hpp
  gui/include/GameDatas/Team.hpp
  gui/src/Engine/Engine.cpp
  gui/src/GUIUpdater/GUIUpdater.cpp
  gui/src/GameDatas/GameData.cpp
  gui/src/GameDatas/Team.cpp
  gui/src/Network/Network.cpp
  gui/src/Render/Render.cpp
  gui/src/main.cpp
  tests/gui/tests/GUIUpdater/TestGUIUpdater.cpp
  tests/gui/tests/GameDatas/TestGameData.cpp
  tests/gui/tests/GameDatas/TestTeam.cpp
Labels: enhancement

#218 Implement all possible tests - Zappy GUI
  gui/Makefile
  gui/include/Event/AEvent.hpp
  gui/src/Event/AEvent.cpp
  tests/gui/tests/Event/TestEvent.cpp
  tests/gui/tests/GUIUpdater/TestGUIUpdater.cpp
  tests/gui/tests/GameDatas/TestGameData.cpp
  tests/gui/tests/GameDatas/TestInventory.cpp
  tests/gui/tests/GameDatas/TestPlayer.cpp
  tests/gui/tests/GameDatas/TestTeam.cpp
  tests/gui/tests/Mocks/TestMocks.cpp
Labels: tests

#278 Create bonus program to manually control the AI - Zappy AI
  ai/README.md
  bonus/ai-controller/Makefile
  bonus/ai-controller/README.md
  bonus/ai-controller/assets/deraumere.png
  bonus/ai-controller/assets/egg.png
  bonus/ai-controller/assets/food.png
  bonus/ai-controller/assets/linemate.png
  bonus/ai-controller/assets/mendiane.png
  bonus/ai-controller/assets/phiras.png
  bonus/ai-controller/assets/player.png
  bonus/ai-controller/assets/sibur.png
  bonus/ai-controller/assets/thystame.png
  bonus/ai-controller/assets/tile.png
  bonus/ai-controller/requirements.txt
  bonus/ai-controller/src/AI.py
  bonus/ai-controller/src/Enum/Action.py
  bonus/ai-controller/src/Enum/Item.py
  bonus/ai-controller/src/Enum/Mode.py
  bonus/ai-controller/src/Enum/Role.py
  bonus/ai-controller/src/Errors/ArgsException.py
  bonus/ai-controller/src/Errors/IError.py
  bonus/ai-controller/src/Network/API.py
  bonus/ai-controller/src/Network/APIException.py
  bonus/ai-controller/src/Player/Inventory.py
  bonus/ai-controller/src/Player/Player.py
  bonus/ai-controller/src/Player/PlayerException.py
  bonus/ai-controller/src/Utils/Message.py
  bonus/ai-controller/src/Utils/Utils.py
  bonus/ai-controller/src/main.py
  bonus/api-ai/README.md
Labels: enhancement

#279 fix: frequency is limited
  server/src/parsing/parse_frequency.c
Labels: enhancement

#275 feat: doxygen-auto-doc pdfs with last main 22/06 last day
  doc/ai-doc/doxygen-auto-doc.pdf
  doc/gui-doc/doxygen-auto-doc.pdf
  doc/server-doc/doxygen-auto-doc.pdf
Labels: documentation

#273 doc(wip): Add readme for the Server module of the project
  doc/server-doc/Zappy_Server_Structure_Diagram .jpg
  doc/server-doc/Zappy_Server_Structure_Diagram .pdf
  server/README.md
Labels: documentation

#281 fix: double free when AI died
  server/src/ai/die.c
Labels: bug
